# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UltraProject1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UltraProject1
  pod 'Alamofire'
  pod 'SnapKit'

  target 'UltraProject1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UltraProject1UITests' do
    # Pods for testing
  end

end
