# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'
pod 'Alamofire', '~> 5.4'
  # Pods for Practice6

end
