# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Practice1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice1
  pod 'Alamofire'
  pod 'Kanna'
  pod 'SnapKit'

end
