# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice1
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SDWebImage'
  pod 'SnapKit'

  target 'Practice1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Practice1UITests' do
    # Pods for testing
  end

end
