# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project5
  pod 'SnapKit'
  pod 'Alamofire'

end
